### ISSUE TITLE
Support regular expressions for an IRI

### ISSUE THREAD

**Issue by yayamamo** [DaniFdezAlvarez/shexer#116]
As in the [ShEx spec.](https://shex.io/shex-primer/index.html), regular expressions can be used to constrain IRIs.
Inversely, it would be beneficial if sheXer generates these regular expressions by scanning a given RDF dataset.
One use case is to check any string fluctuations or spelling errors in IRIs.

**Comment by yayamamo** [comment]
I found [this feature](https://shex.io/shex-primer/index.html#value-sets) and it would be fine for a subject to follow a given prefix.
```
<S>  [<http://a.example/foo>~ ] AND {
  <p1> .
}
```

**Comment by DaniFdezAlvarez** [comment]
@yayamamo I'm starting to work on this. I hope to produce a new release with this feature soon
