### ISSUE TITLE
Triple frequencies in addition to ratios.

### ISSUE THREAD

**Issue by yayamamo** [DaniFdezAlvarez/shexer#126]
sheXer reports the ratio of triples matching an extracted constraint as a ShEx comment as follows.
```
   rdf:type  [sbo:Organ]  ?;
            # 41.02564102564102 % obj: sbo:Organ. Cardinality: {1}
```
It would be nicer if it could report the real number of triples that match.

**Comment by DaniFdezAlvarez** [comment]
It seems perfectly feasible. I'll include this as soon as I can work on sheXer again
