### ISSUE TITLE
ValueError on HTTPS

### ISSUE THREAD

**Issue by xuemduan** [DaniFdezAlvarez/shexer#150]
Hi, 

I got this error message when I try to use shexer to generate SHACL shapes from a RDF graph:

```
/usr/local/lib/python3.10/dist-packages/shexer/io/shacl/formater/shacl_serializer.py in _generate_r_uri_for_str_uri(self, property_str)
    212         elif property_str.startswith("http://"):
    213             return URIRef(property_str)
--> 214         raise ValueError("Check here:", property_str)
    215 
    216     def _is_a_shape(self, target_type):

ValueError: ('Check here:', 'https://www.w3.org/ns/legal#registeredAddress')
```

Is it possible to make this tool supports HTTPS?

Thank you!

Bests,
Xuemin

**Comment by DaniFdezAlvarez** [comment]
@xuemduan , there is a bug indeed, I've got an input file producing a similar error. I'm working on it, I'll close this issue when I launch a new release that I think will fix that. 

Still, if the problem persist with your input after the launch, feel free to reopen it (I'd appreciate if you sahre your input and script in that case).

**Comment by DaniFdezAlvarez** [comment]
I think your bug shouldn't be happening from [release 2.2.2](https://github.com/DaniFdezAlvarez/shexer/releases/tag/2.2.2)
